### ISSUE TITLE
How to get the bot running for non-developer?

### ISSUE THREAD

**Issue by Mokaaaaa** [nuxy/bittrex_autotrader#1]
Mind sharing a running bittrex_autotrader.py with the default settings and where to put the API args.

**Comment by nuxy** [comment]
Running the script should be easy.

**Using a settings file**
- Update the `bittrex_autotrader.conf` with your [Bittrex](https://www.bittrex.com) API credentials and trade settings.
- Ensure the script has execution privileges `chmod 755 bittrex_autotrader.py`
- Ensure the script configuration is in a secure location that has restricted access.
- Run the script: `./bittrex_autotrader.py --conf bittrex_autotrader.conf`

**or, with arguments**
- Ensure the script has execution privileges `chmod 755 bittrex_autotrader.py`
- Pass the following arguments _on script execution_:
```
# ./bittrex_autotrader.py --help
usage: bittrex_autotrader.py [-h] [--conf FILE] --apikey APIKEY --secret
                             SECRET [--market MARKET] [--units UNITS]
                             [--spread SPREAD] [--method METHOD]
                             [--delay DELAY]

optional arguments:
  -h, --help       show this help message and exit
  --conf FILE      Configuration file (bittrex_autotrader.conf)
  --apikey APIKEY  Bittrex issued API key.
  --secret SECRET  Bittrex issued API secret.
  --market MARKET  String literal for the market (ie. BTC-LTC)
  --units UNITS    BUY/SELL total units (default: 1.0)
  --spread SPREAD  BUY/SELL markup/markdown percentage (default: 0.1/0.1)
  --method METHOD  Moving Average calculation method (default: arithmetic)
  --delay DELAY    Seconds to delay order status requests (default: 30)
```

**Comment by Mokaaaaa** [comment]
Hi,
Thank you for taking the time to explain how to get it the script working.
I have tried and followed exactly what you have mentioned above. 
I still face this issue 

> bittrex_autotrader.py: error: argument --apikey is required

I think it's worth to mention I'm using python 2.7.

**Comment by nuxy** [comment]
If you're using the `--conf` method the target file must exist.
```
bittrex_autotrader.py --conf /path/to/bittrex_autotrader.conf
```
If the issue is unrelated to ^ please paste the full command (**without the API key information**).

**Comment by Mokaaaaa** [comment]
Yes, it's working. It requests readline module from humanfriendly. I installed pyreadline and it worked.

> 
> 1. BUY in at markdown (need units to trade)
>   2. SELL out at markup (need liquidity)
> 
>  Enter your choice as a number or unique substring (Control-C aborts):

If I choose 1 I get this:
> Bittex response: MARKET_OFFLINE

If  I choose 2 I get this:

> Desktop\123\bittrex_autotrader.py:405: UserWarning: loadtxt: Empty input file: "<StringIO.StringIO instance at 0x040B05D0>"
>   unpack=True
> 
> Traceback (most recent call last):
> Desktop\123\bittrex_autotrader.py", line 916, in <module>
>     BittrexAutoTraderConfig.values()
> 
> Desktop\123\bittrex_autotrader.py", line 111, in run
>     self.submit_order(next_trade)
> 
> Desktop\123\bittrex_autotrader.py", line 127, in submit_order
>     market_max = round(market_totals.max(), 8)
> 
>   File "C:\Python27\lib\site-packages\numpy\core\_methods.py", line 26, in _amax
>     return umr_maximum(a, axis, None, out, keepdims)
> ValueError: zero-size array to reduction operation maximum which has no identity

**Comment by Mokaaaaa** [comment]
Hey buddy, the market itself was offline. I think it's working.

I'll submit any issue I face.  Thank you.  I'm keeping eye on your project.

**Comment by nuxy** [comment]
> Yes, it's working. It requests readline module from humanfriendly. I installed pyreadline and it worked.

Good to hear.

Note: I only tested this script in _OSX_, _FreeBSD,_ and _Linux_.  This excludes _Windows_ since it's not my choice of OS.  That said, I will update the `make` file to account for _Windows_ environments and the `pyreadline` dependency.

> I'll submit any issue I face. Thank you.  I'm keeping eye on your project.

For future issues, specifically bugs, please submit a new ticket.  Thanks.
